name = "BibFormatter"
uuid = "4e8691f6-bd88-4c22-a28c-d5957cb74d98"
version = "0.1.0"
authors = ["Simon Praetorius <simon.praetorius@tu-dresden.de>"]

[deps]
BibInternal = "2027ae74-3657-4b95-ae00-e2f7d55c3e64"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"

[compat]
BibInternal = "0.3.7"
BibParser = "0.2.3"
Logging = "1"
Test = "1"
julia = "1.6"

[extras]
BibParser = "13533e5b-e1c2-4e57-8cef-cac5e52f6474"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["BibParser", "Test"]
