Base.@kwdef struct Urlbst{S<:BibliographyStyle} <: BibliographyStyle
  base::S
  addeprints::Bool = true
  adddoiresolver::Bool = true
  addpubmedresolver::Bool = true
  inlinelinks::Bool = false
  vars::UrlBstVariables = UrlBstVariables()
end

Urlbst(base::S; kwargs...) where {S<:BibliographyStyle} = Urlbst{S}(; base=base, kwargs...)

module BibliographyStyleUrlbst

using ...BibFormatter: Abbrv, OutputFormat, Urlbst, empty, formatWebReferences, hasWebReferences, possiblySetupInlineLink
import ..BibliographyStyleAbbrv
import BibInternal

"""
    postprocessBlocks(fmt, style, data, blocks) -> Vector{String}

Apply urlbst-specific postprocessing to bibliography blocks generated by the
wrapped base style.

Processing steps:

1. Start from a copy of the already formatted base blocks.
2. If `style.inlinelinks` is enabled and the entry has web references, attach
   a hyperlink to the first suitable primary block.
3. Append explicit URL-reference blocks (`url`, `eprint`, `doi`, `pubmed`) as
   returned by [`formatWebReferences`](@ref), honoring style options.
4. If inline linking is enabled but no suitable block exists, append a fallback
   link block using `vars.linktextstring`.

The function returns a new `Vector{String}` and does not mutate the input.
"""
function postprocessBlocks(fmt::OutputFormat, style::Urlbst, data::BibInternal.Entry, blocks::AbstractVector{<:AbstractString})::Vector{String}
  out = String[blocks...]
  attachedInline = false

  if style.inlinelinks && hasWebReferences(data)
    target = 0
    if length(out) >= 2 && !empty(out[2])
      target = 2
    elseif data.type == "article" && length(out) >= 3 && !empty(out[3])
      target = 3
    end

    if target > 0
      out[target] = possiblySetupInlineLink(
        fmt, out[target], style.vars, data;
        inlinelinks=style.inlinelinks,
        addeprints=style.addeprints,
        adddoiresolver=style.adddoiresolver,
        addpubmedresolver=style.addpubmedresolver,
      )
      attachedInline = true
    end
  end

  # TODO: actually, all urls are appended as one block. It might be better represented as a sentence

  append!(out, formatWebReferences(
    fmt, style.vars, data;
    inlinelinks=style.inlinelinks,
    addeprints=style.addeprints,
    adddoiresolver=style.adddoiresolver,
    addpubmedresolver=style.addpubmedresolver,
  ))

  if style.inlinelinks && hasWebReferences(data) && !attachedInline
    fallback = possiblySetupInlineLink(
      fmt, style.vars.linktextstring, style.vars, data;
      inlinelinks=style.inlinelinks,
      addeprints=style.addeprints,
      adddoiresolver=style.adddoiresolver,
      addpubmedresolver=style.addpubmedresolver,
    )
    push!(out, fallback)
  end

  out
end

"""Format `@webpage` entries following urlbst conventions."""
function webpage(fmt::OutputFormat, style::Urlbst, data::BibInternal.Entry)::Vector{String}
  out = BibliographyStyleAbbrv.Output(fmt)

  if empty(data.authors)
    if !empty(data.editors)
      BibliographyStyleAbbrv.outputNonNull!(out, BibliographyStyleAbbrv.formatEditors(out, data))
    end
  else
    if empty(data.editors)
      BibliographyStyleAbbrv.outputNonNull!(out, BibliographyStyleAbbrv.formatAuthors(out, data))
    else
      @warn "Can't use both 'author' and 'editor' fields in $(data.id)"
    end
  end

  BibliographyStyleAbbrv.newBlock!(out)
  title = BibliographyStyleAbbrv.formatTitle(out, data)
  title = possiblySetupInlineLink(
    fmt, title, style.vars, data;
    inlinelinks=style.inlinelinks,
    addeprints=style.addeprints,
    adddoiresolver=style.adddoiresolver,
    addpubmedresolver=style.addpubmedresolver,
  )
  BibliographyStyleAbbrv.outputCheck!(out, title, "Empty 'title' in $(data.id)")
  BibliographyStyleAbbrv.output!(out, "[" * style.vars.onlinestring * "]")

  if !empty(data.date.year)
    BibliographyStyleAbbrv.newBlock!(out)
    BibliographyStyleAbbrv.outputCheck!(out, BibliographyStyleAbbrv.formatDate(out, data), "Empty 'year' in $(data.id)")
  end

  BibliographyStyleAbbrv.newBlock!(out)
  BibliographyStyleAbbrv.output!(out, data.note)

  postprocessBlocks(fmt, style, data, BibliographyStyleAbbrv.finEntry!(out))
end

end # module BibliographyStyleUrlbst

_postprocess(fmt::OutputFormat, style::Urlbst, data::BibInternal.Entry, blocks::Nothing) = nothing
_postprocess(fmt::OutputFormat, style::Urlbst, data::BibInternal.Entry, blocks::AbstractVector{<:AbstractString}) =
  BibliographyStyleUrlbst.postprocessBlocks(fmt, style, data, blocks)

"""Format `@article` using a wrapped base style and urlbst postprocessing."""
formatArticle(fmt::OutputFormat, style::Urlbst, data::BibInternal.Entry) =
  _postprocess(fmt, style, data, formatArticle(fmt, style.base, data))

"""Format `@book` using a wrapped base style and urlbst postprocessing."""
formatBook(fmt::OutputFormat, style::Urlbst, data::BibInternal.Entry) =
  _postprocess(fmt, style, data, formatBook(fmt, style.base, data))

"""Format `@booklet` using a wrapped base style and urlbst postprocessing."""
formatBooklet(fmt::OutputFormat, style::Urlbst, data::BibInternal.Entry) =
  _postprocess(fmt, style, data, formatBooklet(fmt, style.base, data))

"""Format `@inbook` using a wrapped base style and urlbst postprocessing."""
formatInBook(fmt::OutputFormat, style::Urlbst, data::BibInternal.Entry) =
  _postprocess(fmt, style, data, formatInBook(fmt, style.base, data))

"""Format `@incollection` using a wrapped base style and urlbst postprocessing."""
formatInCollection(fmt::OutputFormat, style::Urlbst, data::BibInternal.Entry) =
  _postprocess(fmt, style, data, formatInCollection(fmt, style.base, data))

"""Format `@manual` using a wrapped base style and urlbst postprocessing."""
formatManual(fmt::OutputFormat, style::Urlbst, data::BibInternal.Entry) =
  _postprocess(fmt, style, data, formatManual(fmt, style.base, data))

"""Format `@mastersthesis` using a wrapped base style and urlbst postprocessing."""
formatMastersThesis(fmt::OutputFormat, style::Urlbst, data::BibInternal.Entry) =
  _postprocess(fmt, style, data, formatMastersThesis(fmt, style.base, data))

"""Format `@misc` using a wrapped base style and urlbst postprocessing."""
formatMisc(fmt::OutputFormat, style::Urlbst, data::BibInternal.Entry) =
  _postprocess(fmt, style, data, formatMisc(fmt, style.base, data))

"""Format `@phdthesis` using a wrapped base style and urlbst postprocessing."""
formatPhDThesis(fmt::OutputFormat, style::Urlbst, data::BibInternal.Entry) =
  _postprocess(fmt, style, data, formatPhDThesis(fmt, style.base, data))

"""Format `@proceedings` using a wrapped base style and urlbst postprocessing."""
formatProceedings(fmt::OutputFormat, style::Urlbst, data::BibInternal.Entry) =
  _postprocess(fmt, style, data, formatProceedings(fmt, style.base, data))

"""Format `@techreport` using a wrapped base style and urlbst postprocessing."""
formatTechreport(fmt::OutputFormat, style::Urlbst, data::BibInternal.Entry) =
  _postprocess(fmt, style, data, formatTechreport(fmt, style.base, data))

"""Format `@unpublished` using a wrapped base style and urlbst postprocessing."""
formatUnpublished(fmt::OutputFormat, style::Urlbst, data::BibInternal.Entry) =
  _postprocess(fmt, style, data, formatUnpublished(fmt, style.base, data))

"""Format `@webpage` entries for urlbst-derived styles."""
formatWebpage(fmt::OutputFormat, style::Urlbst, data::BibInternal.Entry) =
  BibliographyStyleUrlbst.webpage(fmt, style, data)
